services:
  - type: web
    name: tasslelife-cart
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,write_products,write_metaobject_definitions,write_metaobjects
      - key: HOST
        fromService:
          name: tasslelife-cart
          type: web
          property: host
